# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j4primelte/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j4primelte

PRODUCT_COPY_FILES += \
    vendor/samsung/j4primelte/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/samsung/j4primelte/proprietary/vendor/lib/hw/sensors.msm8937.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.msm8937.so \
    vendor/samsung/j4primelte/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so
